# Generated by Django 4.1.6 on 2023-02-12 16:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='path',
            fields=[
                ('path_id', models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.uuid4)),
                ('path_author', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
